SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `40853_intech`.`Personne` ADD COLUMN `Adresse_idAdresse` INT(11) NOT NULL  AFTER `adresse` , 
  ADD CONSTRAINT `fk_Personne_Adresse`
  FOREIGN KEY (`Adresse_idAdresse` )
  REFERENCES `40853_intech`.`Adresse` (`idAdresse` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `fk_Personne_Adresse_idx` (`Adresse_idAdresse` ASC) ;

CREATE  TABLE IF NOT EXISTS `40853_intech`.`Adresse` (
  `idAdresse` INT(11) NOT NULL AUTO_INCREMENT ,
  `num` INT(5) NULL DEFAULT NULL ,
  `rue` VARCHAR(45) NULL DEFAULT NULL ,
  `code` INT(5) NULL DEFAULT NULL ,
  `ville` VARCHAR(45) NULL DEFAULT NULL ,
  `pays` VARCHAR(45) NULL DEFAULT NULL ,
  PRIMARY KEY (`idAdresse`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;